### ISSUE TITLE
Include exception in the log

### ISSUE THREAD

**Issue by caulagi** [andreschaffer/logging-guidelines#1]
The readme says 

> Include exception in the log

I would like to propose that we shouldn't log the stacktrace for an exception. This is mostly because these stack traces are not actionable; at least in a convenient way. We should instead use an error reporting tool like Sentry. I have seen that such a solution (like Sentry) also gives a very good high level overview of the system (a spike in error reports typically indicates a serious problem).

**Comment by andreschaffer** [comment]
Hey @caulagi , wdyt? https://github.com/andreschaffer/logging-guidelines/pull/2

**Comment by caulagi** [comment]
@andreschaffer LGTM

**Comment by andreschaffer** [comment]
🎉
